spring.application.name=api-assinaturas

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/assinaturas_db
spring.datasource.username=root     
spring.datasource.password=root

# O Hibernate (JPA) vai criar e atualizar as tabelas automaticamente para nós
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurações básicas do RabbitMQ (usando as portas padrão)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
